### ISSUE TITLE
Suggestion : button to display images in mobile view

### ISSUE THREAD

**Issue by Draky50110** [Anisotropic/Chameleon-blue#2]
Hello.

By default, my Roundcube instance does NOT display images.
In a desktop view, I can click on "Display images" button, but not on mobile view.
Is it possible to add a button for this, on mobile view ?

Thanks.

**Comment by Anisotropic** [comment]
This skin was not designed for the mobile, and looks like garbage on it. If you use "mobile view" plugin or skin, try to communicate with its creators.
